### ISSUE TITLE
Error when using a refactor tool on cljs

### ISSUE THREAD

**Issue by hellofunk** [clojure-emacs/clj-refactor.el#111]
Thought I'd share what happens if you attempt to use a refactor tool on a cljs file. I guess refactor shouldn't be turned on with a mode hook associated with cljs? I'm not sure. I have elided actual file names below, but it's just a cljs file.

```
ERROR: Unhandled REPL handler exception processing message {:refactor-fn find-symbol, :ns [], :name setup-socket, :file elided.cljs, :op refactor, :id 11, :clj-dir /elided/, :loc-column 19, :loc-line 57}
java.lang.AssertionError: Assert failed: Can't find elided.namespace in classpath
res
	at deps.toolsanalyzerjvm.v0v6v5.clojure.tools.analyzer.jvm$analyze_ns.invoke(jvm.clj:535)
	at deps.toolsanalyzerjvm.v0v6v5.clojure.tools.analyzer.jvm$analyze_ns.invoke(jvm.clj:531)
	at deps.toolsanalyzerjvm.v0v6v5.clojure.tools.analyzer.jvm$analyze_ns.invoke(jvm.clj:530)
	at refactor_nrepl.analyzer$build_ast.invoke(analyzer.clj:52)
	at refactor_nrepl.analyzer$cachable_ast.invoke(analyzer.clj:59)
	at refactor_nrepl.analyzer$ns_ast.invoke(analyzer.clj:65)
	at refactor_nrepl.refactor$find_local_symbol_reply.invoke(refactor.clj:125)
	at refactor_nrepl.refactor$find_symbol_reply.invoke(refactor.clj:143)
	at refactor_nrepl.refactor$wrap_refactor$fn__7328.invoke(refactor.clj:190)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
	at cider.nrepl.middleware.info$wrap_info$fn__2573.invoke(info.clj:262)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
	at refactor_nrepl.ns.clean_ns$wrap_clean_ns$fn__8836.invoke(clean_ns.clj:69)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
	at cider.nrepl.middleware.trace$wrap_trace$fn__3270.invoke(trace.clj:65)

**Comment by expez** [comment]
Most of `clj-refactor` works fine on cljs files as well (by just acting on the syntax, which is the same in most cases), but perhaps we should put a guard in place for the functions that won't work on cljs or cljx files.

**Comment by hellofunk** [comment]
Yes I think that would be wise. You don't want your refactor tools throwing exceptions for any reason like this.

**Comment by expez** [comment]
Any interest in actually solving this issue, @hellofunk?  I think it would be fairly straightforward to add support for cljs.  All we have to do is branch and user [tools.analyzer.js](https://github.com/clojure/tools.analyzer.js) instead of `tools.analyzer.jvm`.  I'd do it myself but I don't really write any cljs these days so I wouldn't be able to test this.

**Comment by hellofunk** [comment]
I might give this a look eventually. I'm curious and would like to help. My time is short this month but I'll keep it in the general orbit of my considerations.

**Comment by expez** [comment]
The refactor-nrepl ops that depend on building an AST will now throw a helpful error message instead of just crashing when they encounter cljs or cljx files.

It might be real easy to plug in the cljs analyzer to just get this to work, but since I don't write any cljs atm I'm tackling other issues first.
