### ISSUE TITLE
"err-info does not exist" on startup

### ISSUE THREAD

**Issue by sp3ctum** [clojure-emacs/clj-refactor.el#211]
Hi, I get this error when I do `lein repl` on Windows 7:
```
Error loading refactor-nrepl.middleware: java.lang.IllegalAccessError: err-info does not
 exist, compiling:(refactor_nrepl/middleware.clj:1:1)
lein.bat : Exception in thread "main" java.lang.RuntimeException: Unable to resolve var:
 refactor-nrepl.middleware/wrap-refactor in this context, compiling:(C:\Users\mvi\AppDat
a\Local\Temp\form-init8544592448507293085.clj:1:3272)
At line:1 char:5
+ lein <<<<  repl
    + CategoryInfo          : NotSpecified: (Exception in th...085.clj:1:3272):String)  
   [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6651)


    at clojure.lang.Compiler.analyze(Compiler.java:6445)


    at clojure.lang.Compiler.analyze(Compiler.java:6406)


    at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3719)

    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)


    at clojure.lang.Compiler.analyze(Compiler.java:6445)


    at clojure.lang.Compiler.analyze(Compiler.java:6406)


    at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3719)

    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)


    at clojure.lang.Compiler.analyze(Compiler.java:6445)


    at clojure.lang.Compiler.access$100(Compiler.java:38)


    at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6050)


    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)


    at clojure.lang.Compiler.analyze(Compiler.java:6445)


    at clojure.lang.Compiler.analyze(Compiler.java:6406)


    at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)


    at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5217)


    at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3846)


    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6642)


    at clojure.lang.Compiler.analyze(Compiler.java:6445)


    at clojure.lang.Compiler.eval(Compiler.java:6700)


    at clojure.lang.Compiler.eval(Compiler.java:6693)


    at clojure.lang.Compiler.eval(Compiler.java:6693)


    at clojure.lang.Compiler.load(Compiler.java:7130)


    at clojure.lang.Compiler.loadFile(Compiler.java:7086)


    at clojure.main$load_script.invoke(main.clj:274)


    at clojure.main$init_opt.invoke(main.clj:279)


    at clojure.main$initialize.invoke(main.clj:307)


    at clojure.main$null_opt.invoke(main.clj:342)


    at clojure.main$main.doInvoke(main.clj:420)


    at clojure.lang.RestFn.invoke(RestFn.java:421)


    at clojure.lang.Var.invoke(Var.java:383)


    at clojure.lang.AFn.applyToHelper(AFn.java:156)


    at clojure.lang.Var.applyTo(Var.java:700)


    at clojure.main.main(main.java:37)


Caused by: java.lang.RuntimeException: Unable to resolve var: refactor-nrepl.middleware/
wrap-refactor in this context


    at clojure.lang.Util.runtimeException(Util.java:221)


    at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:659)


    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)


    ... 34 more



```

This is my leiningen profile:
```lisp
{:user {:java-cmd "C:\\Program Files\\Java\\jdk1.8.0_60\\bin\\java.exe"
        :plugins [[cider/cider-nrepl "0.1.0-SNAPSHOT"]
                  [refactor-nrepl "1.2.0-SNAPSHOT"]]}}
```

**Comment by sp3ctum** [comment]
If I remove the `[refactor-nrepl "1.2.0-SNAPSHOT"]` vector, the repl starts normally.

**Comment by sp3ctum** [comment]
Oops, looks like I specified nrepl ` 0.1` instead of `0.10` . My bad!
