### ISSUE TITLE
Can't get a repl going with 2.0.0{,-SNAPSHOT}

### ISSUE THREAD

**Issue by expez** [clojure-emacs/clj-refactor.el#241]
tldr; you need to use Clojure 1.7 now.

The reason we're bumping the version to `2.0.0-SNAPSHOT` is because we need access to clojure 1.7 to continue development.  We need access to reader conditionals to work on cljc files and the libraries we depend on are also shipping cljc files now, meaning we can't get access to new features if we don't upgrade as well.

When trying to start a repl in a project using 1.6 I got the following backtrace:

```
error in process sentinel: nrepl-server-sentinel: Could not start nREPL server: Error loading refactor-nrepl.middleware: java.lang.ClassNotFoundException: mranderson046.toolsreader.v0v10v0-alpha3.clojure.tools.reader.impl.utils.TaggedLiteral, compiling:(mranderson046/toolsreader/v0v10v0_alpha3/clojure/tools/reader/impl/utils.clj:50:7)
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: refactor-nrepl.middleware/wrap-refactor in this context, compiling:(/tmp/form-init2972309672097433134.clj:1:6888)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6651)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3719)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3719)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.access$100(Compiler.java:38)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6050)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5217)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3846)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6642)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.eval(Compiler.java:6700)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve var: refactor-nrepl.middleware/wrap-refactor in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:659)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	... 33 more
Subprocess failed
```

**Comment by featalion** [comment]
I have the same issue. As temporary workaround I added `[org.clojure/clojure "1.7.0"]` to dev profile's dependencies list.

**Comment by expez** [comment]
> I have the same issue. As temporary workaround I added [org.clojure/clojure "1.7.0"] to dev profile's dependencies list.

This is not a bug and I'll expend no effort trying to work around this.  I realize this might be inconvenient for some, and I'm sorry about that, but this is the only way forward given the nature of 1.7.
