### ISSUE TITLE
Current stable versions of clj-refactor and cider are incompatible

### ISSUE THREAD

**Issue by senescent1** [clojure-emacs/clj-refactor.el#403]
Please cut a release. Cider 0.16.0 and clj-refactor.el 2.3.1 are incompatible. In clj-refactor.el:
```
(defun cljr-clean-ns ()
  "Clean the ns form for the current buffer.

See: https://github.com/clojure-emacs/clj-refactor.el/wiki/cljr-clean-ns"
  (interactive)
  (cljr--ensure-op-supported "clean-ns")
  (cider-eval-ns-form :sync)
  (cljr--clean-ns))
```
In cider-interaction.el:

```
(defun cider-eval-ns-form ()
  "Evaluate the current buffer's namespace form."
  (interactive)
  (when (clojure-find-ns)
    (save-excursion
      (goto-char (match-beginning 0))
      (cider-eval-defun-at-point))))
```
Note that cider-eval-ns-form no longer accepts arguments. In clj-refactor's master branch, cljr-clean-ns no longer passes an argument to cider-eval-ns-form, so I think you just need to make a release of clj-refactor.

**Comment by senescent1** [comment]
Looks like this was fixed in #386 but there hasn't been a release since then.

**Comment by benedekfazekas** [comment]
thanks for flagging this. I am currently looking at java 9 compatibility issues. When that is done it would make sense to release `2.3.2`. Meanwhile feel free to use the latest snapshot which should work fine for latest stable cider or snapshot.

**Comment by CrowsVeldt** [comment]
I just started having issues with `clj-refactor 2.4.0-SNAPSHOT` and `cider 0.18.0snapshot`.

I've looked at [https://github.com/clojure-emacs/refactor-nrepl/issues/221](https://github.com/clojure-emacs/refactor-nrepl/issues/221) and [https://github.com/rundis/clj-light-refactor/pull/11](https://github.com/rundis/clj-light-refactor/pull/11), and I've tried uninstalling and reinstalling all relevant emacs packages a few times. No luck, so far. 

I'm not very experienced with Clojure, emacs, or anything really. So I'm not sure if I'm missing something obvious. Let me know if there's anything I should do.

Stack trace: 

`Error loading refactor-nrepl.middleware: java.io.FileNotFoundException: Could not locate cider/nrepl/middleware/util/misc__init.class or cider/nrepl/middleware/util/misc.clj on classpath., compiling:(refactor_nrepl/middleware.clj:1:1)
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: refactor-nrepl.middleware/wrap-refactor in this context, compiling:(/tmp/form-init5406186762137332029.clj:1:16504)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7010)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3881)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7005)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3881)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7005)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.access$300(Compiler.java:38)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6368)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7003)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.analyze(Compiler.java:6729)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6100)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5460)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:4022)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7001)
	at clojure.lang.Compiler.analyze(Compiler.java:6773)
	at clojure.lang.Compiler.eval(Compiler.java:7059)
	at clojure.lang.Compiler.eval(Compiler.java:7052)
	at clojure.lang.Compiler.load(Compiler.java:7514)
	at clojure.lang.Compiler.loadFile(Compiler.java:7452)
	at clojure.main$load_script.invokeStatic(main.clj:278)
	at clojure.main$init_opt.invokeStatic(main.clj:280)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invokeStatic(main.clj:311)
	at clojure.main$null_opt.invokeStatic(main.clj:345)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve var: refactor-nrepl.middleware/wrap-refactor in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:720)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7003)
	... 34 more
`

**Comment by expez** [comment]
What's the snapshot version of the refactor-nrepl middleware?

**Comment by CrowsVeldt** [comment]
Not sure. I don't have it in the `project.clj`, so I assume it's whatever version get's automatically injected with `cider-jack-in` in emacs.

When I run `cljr-version' I get this: `clj-refactor 2.4.0-SNAPSHOT (package: 20180725.1258), refactor-nrepl is unreachable`.

That certainly doesn't look good to me, but I'm not sure what it should look like.

**Comment by CrowsVeldt** [comment]
I tried setting `cider-inject-dependencies-at-jack-in` to `nil` (as per [the Cider docs](https://cider.readthedocs.io/en/latest/installation/#ciders-nrepl-middleware)), and adding `refactor-nrepl` to the `project.clj`, but I couldn't get that to work either. I didn't save the error message I got the, but I could give it a go again if it would be useful.

**Comment by bbatsov** [comment]
That's likely related to https://github.com/clojure-emacs/cider-nrepl/commit/15d87747f790d300b0f13eef2e5bdc87b9dfd4ec and the fact that refactor-nrepl doesn't support nREPL 0.4.

**Comment by shen-tian** [comment]
[cider/cifer-nrepl "0.18.0"] is out. Seems to work fine with [refactor-nrepl "2.4.0"]

**Comment by expez** [comment]
Yes, this was solved by the latest releases made by @bbatsov.
